travis:
  secure:
    BINSTAR_TOKEN: TVsUQcICVnY1sz0TaGUI8ND2J9f69bQNynijGWAjphbyuDessCZN95AKcieKBz6D7qeOEOa7HOGaJAmO3iTpyNayKGJtOHGcaBVuxW1OJ1buSmnXksoXYeuXpt3zl4oRyLT4BmcLpq9N/iWvzSjLCJSFKUfyS0VmjYocIoLYiVIvUt+8T2E4X1vRgIrn24R+kv0oAhGKadtTPQgTAsTC1dFwJgqVLarxm4GdegnQRr19uLgzQ1++PUsckP460rC1VVli1XuIKAvrNNbcBpcVd75SJyNfwlQq7vOd97EwqNCTRYEOkwVrWD/w5q91TNcnFXcZm0Py2j7DiS675UnQytzuwHmzxzLF7kRnhFRT2NOtlsKYPpxBt+6zh7YC6P1jS0UI9VwsI2Ur9mAi3V52la+laUDabuAFNRoB0esrDfLYSg2Lujruk7q0BOuSc+5DSv6PFSDAbG0RShX6CpGj3En/X9BKNYtTxcKcO07cbuUw5H7i/DTEtaQmvJ5f0ZU1BNTAHIZAnDm2czu4HvpxyxLw9L202QSpRqBnGh5RfFO4B0i4Bz5sZdynSBKP04RMVh3Z3oa/Sk+7oQfaroMndV+AQmAaYGqVqYlbuRJoFiZkbI7HDSsrgx4RGOtdqh9jNE4TfgwzECfIfEzAUgQM8YzwR864Di/ENNVLx4BRTZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
