travis:
  secure:
    BINSTAR_TOKEN: bprJYsud2AOaJtsBDljFt68O/w8p29Z8SXa4oSPZjJIN2gwE9wh/NYLDbPLpDjrAIybd122QpYlYsBksQD0zv6A5Gtc1drxt2e15H8d4AvAZ9WDZAcV8rLjzYXpEVo7VqlBwegXWI+bcfnc2qJ3olvonqZtNEecLbNbuM/oG5qfts46SFL4n4yegYXH3wGWkbnSmO66lbKy/+zQyv+/cTDBRFMiF/JsOz3hlZrOu0/Cvx32mL5goRhin9NLJWKpO4CECOUpcs49avlQf6uuKhc4pDhRoRnOrMflmanjEb8A5spCNbUVqsepK6UuyPl6CeX15Y8JCVmzKodW7MoBTXpYQ+BzAjVIabmQUVmDOBFfGFJNFi+NYgcWn/fQJPxUR+XpCkPGeBL+vpO/o1Ny2Em80SrOwzwOIQYbLagk3CiuBqQnO7eo3ae+VTHO1idnXEVLfn7NJTc9opZ4rr3uWVrz1BUU4WFQu87ZW1a/y65hZOUiC3Axd7gNRaQ62R9BFVDcuOKkV1Mfrwo+hp7C4bUvX0r7X0Ky+7Ij6ji1dq72Uk6qKNB4a1J6SiTxYtTl48eAhhxqR6ZubpbHAJ+4taG/z1naZsqH6UNZSHoQg9axV4BQCbW2Sj+U4H21UMoDy9UAFhhzZHZ/Ccem/ao2O5DUdTs3Ch9umpJaKD77TpXs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
