travis:
  secure:
    BINSTAR_TOKEN: YEwOSNcclATwIOxaj0iMRyH9MDCjlpZymTqwzoAvywD0TK3YHRXnNc3HOYxWlIx01H6MxVRMZrq4VjgtPhFBn3kloxwQvtWNQTadDpO541jwu04/deIiG+WF6gR0PT5F05vqWAUR2eckBjnB3cCu2idv7hvJ0TISbF/3aanMRvKJuF1XMDvUzetj/Ij5/bvL2tIdoqAMtM49zHqoiQ2wchS5iFFZjpR4dQ2Cp8reUWcKn+737KL2PC8CxthC5dT7WIoA9II3tIL8aBonMdzRTnSSfDOqmcrtFKFegDArbiSqhUpO7YW6FMf2JdQzgU9tl1lisXqhpqcqUIayyuk/ddzi6I+ImNbj8c4m/hT/9Msd28CdeANf8AiGLKydYv8yaKiLdMQ+XcIt5wSxwFWMjUFkSbjm+Mg5fwXkfh3d0w13IFCbnNc/FB/8P0HYnMgzVkvJkIXSGOdLDnArBuS9/R3EAl1EKLbo46uwXh9KtXhSa1oOqKPYhuJY70gSFTB6T+B5h9c1KtW8gkZeOBBPv+/Qb/NacNJm3ikCV3x64CIevAeEJduIg3/MkWcig/SuC4/yr/HsGn/qQqzH0NBhYF75h/mtNPp0AvPAaR9AroDg5/xPToWJydg+5ngjjPDpkWT+vokLrEICIrDKVAhHLMW2PP6TGmZny30CNJgAvsE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
